version: '3.2'

services:
  wls:
    image: 1221-oradb-medrec:latest 
    ports:
      - 7011:7011
    depends_on:
       - orcldb

  orcldb:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - db-oracle:/ORCL

volumes:
  db-oracle:
