version: '3.2'

services:
  wls:
    build: .
    ports:
      - 7011:7011
    depends_on:
       - database
    networks:
      - new

  database:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: orcldb
    networks:
      - new
    ports:
      - 1521:1521
      - 5500:5500

networks:
  new:
